spring.application.name=demo
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.datasource.url=jdbc:h2:file:./Books_db

# 'update' means: "Keep the data, just change the tables if I add new fields."
spring.jpa.hibernate.ddl-auto=update

# . Show me the SQL in the logs so I can see it working
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Keep the console active so you can see the data
spring.h2.console.enabled=true
